config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "chart/top_albums#index"

  namespace :chart do
    resources :top_albums, only: [:index]
    resources :top_tracks, only: [:index]
    resources :top_artists, only: [:index]
    resources :top_playlists, only: [:index]
    resources :top_podcasts, only: [:index]
  end

  resources :albums, only: [:show]
  resources :tracks, only: [:show]
  resources :artists, only: [:show]
  resources :playlists, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def show
        @album = @client.album(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from DeezerApi::Client::DataNotFound, with: :data_not_found
    rescue_from DeezerApi::Client::QueryInvalid, with: :query_invalid

    before_action :initialize_client

    private
        def initialize_client
            @client = DeezerApi::Client.new
        end

        def data_not_found
            render plain: 'Data Not Found'
        end

        def query_invalid
            render plain: 'Query Invalid'
        end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def show
        @artist = @client.artist(params[:id])
        @top_tracklist = @client.artist_top_tracklist(params[:id])
        @related_artists = @client.related_artists(params[:id])
    end
end

app/controllers/chart/top_albums_controller.rb
class Chart::TopAlbumsController < ApplicationController
    def index
        @top_albums = @client.chart("albums")
    end
end

app/controllers/chart/top_artists_controller.rb
class Chart::TopArtistsController < ApplicationController
    def index
        @top_artists = @client.chart("artists")
    end
end

app/controllers/chart/top_playlists_controller.rb
class Chart::TopPlaylistsController < ApplicationController
    def index
        @top_playlists = @client.chart("playlists")
    end
end

app/controllers/chart/top_podcasts_controller.rb
class Chart::TopPodcastsController < ApplicationController
    def index
        @top_podcasts = @client.chart("podcasts")
    end
end

app/controllers/chart/top_tracks_controller.rb
class Chart::TopTracksController < ApplicationController
    def index
        @top_tracks = @client.chart("tracks")
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    def show
        @playlist = @client.playlist(params[:id])
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def show
        @track = @client.track(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/chart/album_helper.rb
module Chart::AlbumHelper
end

app/helpers/chart/top_artists_helper.rb
module Chart::TopArtistsHelper
end

app/helpers/chart/top_playlists_helper.rb
module Chart::TopPlaylistsHelper
end

app/helpers/chart/top_podcasts_helper.rb
module Chart::TopPodcastsHelper
end

app/helpers/chart/top_tracks_helper.rb
module Chart::TopTracksHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/show.html.erb
<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-auto md-auto">
            <h1 class="text-center fs-1 fw-bold"><%= @album.title %></h1>
            <h3 class="text-center fs-3 fw-semibold">by <%= link_to @album.artist.name, artist_path(@album.artist.id) %></h3>
            <img src="<%= @album.cover_big %>" class="img-thumbnail mx-auto d-block" alt="<%= @album.title %> small album cover">
        </div>
        <div class="col-auto md-auto">
            <h2 class="fs-4 fw-semibold">Tracks</h2>
            <ol>
                <% @album.tracks.data.each do |track| %>
                    <li class="fs-5"><%= link_to track.title, track_path(track.id) %>
                <% end %>
            </ol>
        </div>
    </div>
</div>

app/views/artists/show.html.erb
<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-auto md-auto">
            <h1 class="text-center fs-1 fw-bold"><%= @artist.name %></h1>
            <img src="<%= @artist.picture_big %>" class="img-thumbnail mx-auto d-block" alt="<%= @artist.name %> big artist picture">
        </div>
        <div class="col-auto md-auto align-self-center">
            <h2 class="fs-4 fw-semibold">Top Tracks</h2>
            <ol>
                <% @top_tracklist.data.each do |track| %>
                    <li class="fs-5"><%= link_to track.title, track_path(track.id) %>
                <% end %>
            </ol>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <h2 class="fs-2 fw-semibold text-center">Related Artists</h2>
        <% @related_artists.data.each do |artist| %>
            <div class="col-auto my-2">
                <div class="card" style="width: 18rem;">
                    <img src="<%= artist.picture_big %>" class="card-img-top" alt="<%= artist.name %> big artist picture">
                    <div class="card-body text-center fs-5 fw-semibold">
                        <%= link_to artist.name, artist_path(artist.id) %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/chart/top_albums/index.html.erb
<div class="container-sm my-5">
    <h1 class="fw-bold fs-1 text-center">Top 10 Albums</h1>
    <table class="table align-middle">
        <tbody>
            <% @top_albums.each_with_index do |album, i| %>
                <tr>
                    <th scope="row" class="fs-5">#<%= i + 1 %></th>
                    <td><img src="<%= album.cover_small %>" class="img-thumbnail" alt="<%= album.title %> small album cover"></td>
                    <td><%= link_to album.title, album_path(album.id), class: "fs-5 fw-semibold" %></td>
                    <td>by <%= link_to album.artist.name, artist_path(album.artist.id) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/chart/top_artists/index.html.erb
<div class="container-sm my-5">
    <h1 class="fw-bold fs-1 text-center">Top 10 Artists</h1>
    <table class="table align-middle">
        <tbody>
            <% @top_artists.each_with_index do |artist, i| %>
                <tr>
                    <th scope="row" class="fs-5">#<%= i + 1 %></th>
                    <td><img src="<%= artist.picture_small %>" class="img-thumbnail" alt="<%= artist.name %> small artist picture"></td>
                    <td class="fs-5 fw-semibold"><%= link_to artist.name, artist_path(artist.id)%></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/chart/top_playlists/index.html.erb
<div class="container-sm my-5">
    <h1 class="fw-bold fs-1 text-center">Top 10 Playlists</h1>
    <table class="table align-middle">
        <tbody>
            <% @top_playlists.each_with_index do |playlist, i| %>
                <tr>
                    <th scope="row" class="fs-5">#<%= i + 1 %></th>
                    <td><img src="<%= playlist.picture_small %>" class="img-thumbnail" alt="<%= playlist.title%> small playlist picture"></td>
                    <td><%= link_to playlist.title, playlist_path(playlist.id), class: "fs-5 fw-semibold" %></td>
                    <td>by <%= playlist.user.name %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/chart/top_podcasts/index.html.erb
<div class="container-sm my-5">
    <h1 class="fw-bold fs-1 text-center">Top 10 Podcasts</h1>
    <table class="table align-middle">
        <tbody>
            <% @top_podcasts.each_with_index do |podcast, i| %>
                <tr>
                    <th scope="row" class="fs-5">#<%= i + 1 %></th>
                    <td><img src="<%= podcast.picture_small %>" class="img-thumbnail" alt="<%= podcast.title %> small podcast picture"></td>
                    <td class="fs-5 fw-semibold"><%= podcast.title %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/chart/top_tracks/index.html.erb
<div class="container-sm my-5">
    <h1 class="fw-bold fs-1 text-center">Top 10 Tracks</h1>
    <table class="table align-middle">
        <tbody>
            <% @top_tracks.each_with_index do |track, i| %>
                <tr>
                    <th scope="row" class="fs-5">#<%= i + 1 %></th>
                    <td><img src="<%= track.artist.picture_small %>" class="img-thumbnail" alt="<%= track.artist.name %> small artist picture"></td>
                    <td><%= link_to track.title, track_path(track.id), class: "fs-5 fw-semibold" %></td>
                    <td>by <%= link_to track.artist.name, artist_path(track.artist.id) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/playlists/show.html.erb
<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-auto md-auto">
            <h1 class="text-center fs-1 fw-bold"><%= @playlist.title %></h1>
            <h3 class="text-center fs-3 fw-semibold">by <%= @playlist.creator["name"] %></h3>
            <img src="<%= @playlist.picture_big %>" class="img-thumbnail mx-auto d-block" alt="<%= @playlist.title %> big playlist picture">
        </div>
        <div class="col-auto md-auto">
            <p class="fs-5 fw-semibold fst-italic text-center"><%= @playlist.description %></p>
            <h2 class="fs-4 fw-semibold">Tracks</h2>
            <table class="table align-middle">
                <tbody>
                    <% @playlist.tracks.data.each_with_index do |track, i| %>
                        <tr>
                            <th scope="row"><%= i + 1 %></th>
                            <td class="fs-5"><%= link_to track.title, track_path(track.id) %></td>
                            <td>by <%= link_to track.artist.name, artist_path(track.artist.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/tracks/show.html.erb
<div class="container-sm my-4">
    <div class="row justify-content-center">
        <div class="col-auto md-auto">
            <img src="<%= @track.artist.picture_big %>" class="img-thumbnail mx-auto d-block" alt="<%= @track.artist.name %> big artist picture">
        </div>
        <div class="col-auto md-auto text-center align-self-center">
            <h1 class="text-center fs-1 fw-bold"><%= @track.title %></h1>
            <h5 class="text-center">from <%= link_to @track.album.title, album_path(@track.album.id) %></h5>
            <h3 class="text-center fs-3 fw-semibold">by <%= link_to @track.artist.name, artist_path(@track.artist.id) %></h3>
            <%= audio_tag @track.preview, controls: true %>
        </div>
    </div>
</div>