config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "chart/top_albums#index"

  namespace :chart do
    resources :top_albums, only: [:index]
    resources :top_tracks, only: [:index]
    resources :top_artists, only: [:index]
    resources :top_playlists, only: [:index]
    resources :top_podcasts, only: [:index]
  end

  resources :albums, only: [:show]
  resources :tracks, only: [:show]
  resources :artists, only: [:show]
  resources :playlists, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def show
        @album = @client.album(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from DeezerApi::Client::DataNotFound, with: :data_not_found
    rescue_from DeezerApi::Client::QueryInvalid, with: :query_invalid

    before_action :initialize_client

    private
        def initialize_client
            @client = DeezerApi::Client.new
        end

        def data_not_found
            render plain: 'Data Not Found'
        end

        def query_invalid
            render plain: 'Query Invalid'
        end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def show
        @artist = @client.artist(params[:id])
        @top_tracklist = @client.artist_top_tracklist(params[:id])
        @related_artists = @client.related_artists(params[:id])
    end
end

app/controllers/chart/top_albums_controller.rb
class Chart::TopAlbumsController < ApplicationController
    def index
        @top_albums = @client.chart("albums")
    end
end

app/controllers/chart/top_artists_controller.rb
class Chart::TopArtistsController < ApplicationController
    def index
        @top_artists = @client.chart("artists")
    end
end

app/controllers/chart/top_podcasts_controller.rb
class Chart::TopPodcastsController < ApplicationController
    def index
        @top_podcasts = @client.chart("podcasts")
    end
end

app/controllers/chart/top_tracks_controller.rb
class Chart::TopTracksController < ApplicationController
    def index
        @top_tracks = @client.chart("tracks")
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    def show
        @playlist = @client.playlist(params[:id])
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def show
        @track = @client.track(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/chart/album_helper.rb
module Chart::AlbumHelper
end

app/helpers/chart/top_artists_helper.rb
module Chart::TopArtistsHelper
end

app/helpers/chart/top_playlists_helper.rb
module Chart::TopPlaylistsHelper
end

app/helpers/chart/top_podcasts_helper.rb
module Chart::TopPodcastsHelper
end

app/helpers/chart/top_tracks_helper.rb
module Chart::TopTracksHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiWrapper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold fs-4 text-bg-dark" href="#">deezer charts</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><%= link_to "Top Albums", chart_top_albums_path, class: "dropdown-item nav-link text-bg-dark" %></li>
            <li class="nav-item"><%= link_to "Top Tracks", chart_top_tracks_path, class: "dropdown-item nav-link text-bg-dark" %></li>
            <li class="nav-item"><%= link_to "Top Artists", chart_top_artists_path, class: "dropdown-item nav-link text-bg-dark" %></li>
            <li class="nav-item"><%= link_to "Top Playlists", chart_top_playlists_path, class: "dropdown-item nav-link text-bg-dark" %></li>
            <li class="nav-item"><%= link_to "Top Podcasts", chart_top_podcasts_path, class: "dropdown-item nav-link text-bg-dark" %></li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>